Update BloodyRat

diff --git a/BloodyRat/BloodyRat b/BloodyRat/BloodyRat
--- a/BloodyRat/BloodyRat
+++ b/BloodyRat/BloodyRat
@@ -1,5 +1,107 @@
 #! /bin/bash
-#HELLO HEY BRO
+
+function update() {
+	version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/BloodyRat/main/BloodyRat | grep -w "VERSION=" | head -n1)
+	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
+	if [ "${1}" != "-u" ] || [ "${1}" != "--update" ]; then
+		[ ${latest_version} != ${VERSION} ] && echo && msg "shark update is available !!" && sleep 2.5 && echo && msg "Run shark -u , shark --update" && echo && exit 1;	       
+        fi
+}
+
+function connection() {
+        ping -c 1 google.com > /dev/null 2>&1
+        if [[ "$?" != 0 ]];then
+                error_msg "No internet"
+        exit 0
+        fi
+}
+
+function internet() {	
+	ping -c 1 google.com > /dev/null 2>&1
+        if [ $? -eq 0 -a ! "${1}" = "--update" ] && [ $? -eq 0 -a ! "$1" = "-u" ];then		
+                update
+	fi
+}
+
+function main_update() {
+	launch="updating shark"
+	splashdown="updated shark";echo
+	os;(wget -q https://github.com/Bhaviktutorials/shark/raw/master/shark -O ${shark}/shark && rm -rf ${old_shark} && cp -rf ${shark}/shark $BIN && chmod 777 $BIN/shark) & spinner
+}
+
+function check_update() {	
+        connection
+        version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/shark/master/shark | grep -w "VERSION=" | head -n1)
+	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
+        if [ ${latest_version} = ${VERSION} ];then		
+                echo -e "\tReading \tpackage \tlists... \tDone
+                         \tBuilding \tdependency \ttree       
+                         \tReading \tstate \tinformation... \tDone
+                         \tshark \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
+	        exit 1
+	else
+		main_update
+		exit 1
+	fi
+}
+
+usage() {
+        cat <<EOF
+Usage: $(basename $0) [OPTIONS] available
+shark - future of phishing is here,
+A shark is a tool that will help you \do Phishing \in an advanced way so no one checks and identify that you are doing phishing.
+Copyright 2020 <ashishsingh103020@gmail.com>
+Options:
+  -u, --update      Update shark
+  -v, --version     Display the current shark version installed on your device
+  -h, --help        Print this help message
+  -a, --assist      List detail discription of shark
+  -p, --purge       Uninstall shark
+  --fix-ngrok       Fix port forwarding issue 
+  --fix-patches     Check missing packages & fix patches
+  --fix-cloudshell  Restart Vm and cloudshell & fix patches
+For additional info, see: https://github.com/Bhaviktutorials/shark
+EOF
+}
+
+ 
+#getopts argument
+while true; do
+        case "$1" in		
+                -u|--update)			
+	                check_update
+			;;
+
+                -h|--help)			
+                        usage       
+                        exit 1
+			;;
+
+                -v|--version)			
+                        printf "version $VERSION\n"
+                        exit 1
+                        ;;
+
+		--fix-apkbuilder)			
+			sed -i -e 's/\r$//' ${hackadroid_main}/setup
+			chmod 777 ${hackadroid_main}/setup
+		        ${hackadroid_main}/setup
+			exit 1
+			;;
+
+                -*)			
+                        echo "ERROR: unknown option '$1'" 1>&2
+                        echo "see '--help' for usage" 1>&2
+                        exit 1
+                        ;;
+
+                *)	
+                        f=$1
+                        break			
+                        ;;
+	esac
+        shift
+done
 
 user_name=`logname`
 function os() {
